apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: oauth-agent
spec:
  selector:
    app: demo-service
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service-external
  namespace: oauth-agent
spec:
  selector:
    app: demo-service
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30500
  type: NodePort
