apiVersion: v1
kind: Service
metadata:
  name: consent-ui
  namespace: oauth-agent
spec:
  selector:
    app: consent-ui
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: consent-ui-external
  namespace: oauth-agent
spec:
  selector:
    app: consent-ui
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30800
  type: NodePort
