apiVersion: v1
kind: Service
metadata:
  name: devoops-agent
  namespace: devoops
spec:
  selector:
    app: devoops-agent
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
